[font]
	normal = { family = "Fixedsys Excelsior" }
	#normal = { family = "Iosevka Slab" }
	#normal = { family = "Hack", style="Bold" }
	#normal = { family = "Terminus" }
	#normal = { family = "ProggyClean", style ="Regular" }
	size = 12

[colors]
	[colors.primary]
	foreground = "#DDDDDD"
	background = "#000000"
	
[window]
	opacity = 0.9

[cursor]
	style = { shape = "Block", blinking = "Always"}	
	blink_interval = 250
	blink_timeout = 0




